### PR TITLE
Prepare gemspec for release

### PR DESCRIPTION
**Pull request by ronen**
@stenver  just renaming the gemspec.

At first I thought I need to list myself as author in the gemspec to be able to push a release on rubygems, but then I looked again at the rubygems docs and that doesn't seem to be the case.

### CODE REVIEW

**Comment by stenver** [comment]
You can add yourself as co-author if you wish :) I wont merge until you respond to this message.

**Comment by ronen** [comment]
no need, thanks :)  go ahead and merge.   i'll release the gem to rubygems, and can add you as a co-owner if you have a rubygems account

**Comment by stenver** [comment]
Yes I do, its stenver there as well

**Comment by stenver** [comment]
https://rubygems.org/profiles/stenver

**Comment by ronen** [comment]
OK, gem released, you and I are co-owners!

**Comment by stenver** [comment]
Sounds good! Thanks for all the help

**Comment by ronen** [comment]
Thanks for the new gem!

FYI  I added a reference to it in the main schema_plus [README](https://github.com/SchemaPlus/schema_plus)

**Pull request merged**
